repositories {
    mavenCentral()
}

dependencies {
    implementation group: 'com.google.inject', name: 'guice', version: '7.0.0'
    implementation group: 'ru.vyarus', name: 'dropwizard-guicey', version: '7.1.4'
    implementation group: 'com.netflix.feign', name: 'feign-core', version: feignVersion
    implementation group: 'com.netflix.feign', name: 'feign-jackson', version: feignVersion
    implementation group: 'com.netflix.feign', name: 'feign-jaxrs', version: feignVersion
    implementation group: 'com.netflix.feign', name: 'feign-okhttp', version: feignVersion
    implementation group: 'com.netflix.feign', name: 'feign-slf4j', version: feignVersion
    implementation group: 'io.dropwizard', name: 'dropwizard-core', version: dropwizardVersion
    compileOnly group: 'org.projectlombok', name: 'lombok', version: '1.18.22'
    compileOnly("jakarta.platform:jakarta.jakartaee-api:11.0.0-RC1")
    annotationProcessor group: 'org.projectlombok', name: 'lombok', version: lombokVersion
    implementation group: 'commons-io', name: 'commons-io', version: '2.14.0'
}

jib {
    from {
        image = 'openjdk:21'
    }
    to {
        image = 'localhost:5000/calculator-client'
        tags = ['latest']
    }
    container {
        mainClass = 'ru.akiselev.calculator.client.CalculatorClientApp'
        ports = ['8090', '8091']
        allowInsecureRegistries = true
        jvmFlags = ['--enable-preview']
        args = ['server', 'application.yml']
    }
}
